### ISSUE TITLE
Drip's docs link to their fork, NPM copy is from your repo (which has a different API)

### ISSUE THREAD

**Issue by wwalser** [samudary/drip-nodejs#2]
Was just looking to use this and noticed that following links from Drip's documentation leads to https://github.com/DripEmail/drip-nodejs but using `npm install` gives a more up-to-date version from your repo.

This means that the documentation's API does not match the code that's been installed. For example, the subscribers api no longer takes both `email` and `payload`.

Edit: In practice, it's clear that there are several other issues with the library. If I put together well-written pull requests are you/the Drip team willing to accept them?

**Comment by samudary** [comment]
Hey, thanks for pointing this out. I just merged the Drip fork with the main upstream from this repo. So all should be in sync.

I definitely agree that there are some opportunities for improvement in the library. This version is a first step towards ensuring that a Node package is available since we were getting quite a bit more demand for this. Will definitely be gradually making improvements.

Just reviewed your recent PR and that looks good and is now merged. We'd be happy to accept any contributions you may have.

Thanks!

**Comment by wwalser** [comment]
Thanks @samudary 👍
